name: CI-PhotoAcoustic

on:
  # Trigger the workflow on push to master or pull request
  # to be merged in master
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    env:
      DEVITO_ARCH: gcc-9
      DEVITO_LANGUAGE: "openmp"
      DEVITO_LOGGING: "ERROR"
      OMP_NUM_THREADS: 2

    strategy:
      fail-fast: false

      matrix:
        version:
          - '1.6'
          - '1.7'
          - '1.8'
        os:
          - ubuntu-latest
        arch:
          - x64

        include:
          - os: macos-latest
            version: '1'
            arch: x64

    steps:
      - name: Checkout PhotoAcoustic
        uses: actions/checkout@v3

      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Install GCC 9
        if : runner.os == 'macOS'
        run : brew install gcc@9

      - name: Run tests
        uses: julia-actions/julia-runtest@latest

      - name: Install Examples packages
        run: |
          julia -e 'using Pkg;Pkg.add(["Statistics", "LinearAlgebra", "PyPlot", "IterativeSolvers"])'

      - name: Run examples
        run: |
          julia --color=yes --project examples/basic_photo_operator_2d.jl
          julia --color=yes --project examples/basic_photo_operator_3d.jl
          julia --color=yes --project examples/least_squares.jl