name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: julia-actions/setup-julia@latest
      
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      - name: Convert notebook
        run: |
          pip install --upgrade jupyter Pygments "MarkupSafe==2.0.1" "jinja2<3.1"
          jupyter nbconvert --to markdown --output-dir='../../docs/src' --output LearnedPrior Flux_AD_Integration_Deep_Prior.ipynb
          jupyter nbconvert --to markdown --output-dir='../../docs/src' --output LSQR Least_Squares_Iterative_Solvers_2D.ipynb
        working-directory: examples/notebooks/

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
        run: julia --project=docs/ docs/make.jl
